char * twitter_pin_auth_begin (lph_t *handle);
char * twitter_pin_auth_finish (lph_t *handle, const char *pin);
void print_oauth_params (kv_t *i, va_list ap);
void print_extra_params (kv_t *i, va_list ap);
void print_query_str (kv_t *i, va_list ap);
int send_signed_https (oauth_r_t *oreq);
int send_signed_http (oauth_r_t *oreq);
lph_t * libpummarola_init (const char *oauth_consumer_key, const char *oauth_consumer_secret);
void libpummarola_destroy (lph_t *handle);
void get_user_timeline (lph_t *handle, char *user);
