</$objtype/mkfile

CC=pcc
CFLAGS=-I. -B -c -DPLAN9

LIB=libeitec.a$O

OFILES= \
	lc_byte.$O\
	lc_list.$O\
	lc_md5.$O\

</sys/src/cmd/mklib

install:V:	$LIB
	date

$LIB:	$LIBOBJ
	ar vu $LIB $OFILES
	
clean:
	rm -f *.[$OS] *.a[$OS]
